src/Markri/Bundle/OrganistBundle/Form/ApplicationCreateType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;

class ApplicationCreateType extends HorizontalAbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array(
                'label' => 'Name *')
            )
            ->add('customer', 'text', array(
                'label' => 'Customer / Groupname',
                'required' => false)
            )
            ->add('keyname', 'text', array(
                'max_length'=>16,
                'label'=>'Unique technical name (max 16 chars) * ',
                'required' => true)
            )
            ->add('applicationType', 'applicationtype_choicelist', array(
                    'label'=>'Application type *',
                    'attr' => array('data-help' => 'This has effect on the default shared files and folders'),
                    'required'=>true )
            )
            ->add('scmService', 'versioning_choicelist', array(
                'label'=>'Versioning service *',
                'required'=>true )
            )
            ->add('scmUrl', 'text', array(
                'label'=>'Versioning URL *',
                'attr' => array('data-help' => 'e.g. git@bitbucket.org:netvlies/my_project.git'),
                'required'=>true )
            )
            ->add('deploymentStrategy', 'strategy_choicelist', array(
                    'label' => 'Deployment strategy',
                )
            );
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'application_create';
    }

}

src/Markri/Bundle/OrganistBundle/Form/ApplicationDeployType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ApplicationDeployType extends HorizontalAbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $app = $options['app'];

        $builder
            ->add('target', 'target_choicelist', array(
                'label' => 'Target *',
                'app' => $app,
                'required' => true
            ))
            ->add('revision', 'reference_choicelist', array(
                'label' => 'Reference *',
                'app' => $app,
                'required' => true
            ));
    }

    public function setDefaultOptions(OptionsResolverInterface $options)
    {
        $options->setDefaults(array(
           'app' => null,
        ));
    }

    public function getName()
    {
        return 'markri_organistbundle_applicationdeploy';
    }


}

src/Markri/Bundle/OrganistBundle/Form/ApplicationEditType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form;

use Markri\Bundle\OrganistBundle\Form\ChoiceList\StrategyType;
use Symfony\Component\Form\FormBuilderInterface;

class ApplicationEditType extends HorizontalAbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array(
                'label' => 'Name *')
            )
            ->add('customer', 'text', array(
                'label' => 'Customer / Groupname',
                'required' => false)
            )
            ->add('buildStatusBadge1', 'text', array(
                'label' => 'Build badge 1',
                'required' => false)
            )
            ->add('buildStatusBadge2', 'text', array(
                'label' => 'Build badge 2',
                'required' => false)
            )
            ->add('deploymentStrategy', StrategyType::class
            )
            ->add('userFiles', 'onetomany', array(
                'label' => 'Shared files and directories',
                'type' => new UserFileType(),
                'allow_delete' => true,
                'allow_add'    => true,
                'by_reference' => false,
                'prototype' => true,
                'prototype_name' => '__name__',
                'layoutmacro' => 'OrganistBundle:Form:macro-onetomany-userfiles.html.twig'
                )
            );
    }


    public function getName()
    {
        return 'application_edit';
    }

}

src/Markri/Bundle/OrganistBundle/Form/ApplicationRollbackType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ApplicationRollbackType extends HorizontalAbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $app = $options['app'];

        $builder
            ->add('target', 'target_choicelist', array(
                'label' => 'Target *',
                'app' => $app,
                'attr' => array('data-help'=>'This works just like ctrl-z. (It will undo last succesfull deployment).'),
                'required' => true
            ));

    }

    public function setDefaultOptions(OptionsResolverInterface $options)
    {
        $options->setDefaults(
            array(
                'app' => null
            )
        );
    }

    public function getName()
    {
        return 'markri_organistbundle_applicationrollback';
    }

}

src/Markri/Bundle/OrganistBundle/Form/ApplicationSetupType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ApplicationSetupType extends HorizontalAbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $app = $options['app'];

        $builder
            ->add('target', 'target_choicelist', array(
                'label' => 'Target *',
                'app' => $app,
                'required' => true
            ));
    }

    public function setDefaultOptions(OptionsResolverInterface $options)
    {
        $options->setDefaults(array(
           'app' => null,
        ));
    }

    public function getName()
    {
        return 'markri_organistbundle_applicationsetup';
    }

}

src/Markri/Bundle/OrganistBundle/Form/ApplicationsSelectType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class ApplicationsSelectType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('application', 'entity', array(
                'class' => 'Markri\Bundle\OrganistBundle\Entity\Application',
                'property' => 'keyName'
            )
        );
    }


    public function getName()
    {
        return 'markri_organistbundle_application_select';
    }

}

src/Markri/Bundle/OrganistBundle/Form/ChoiceList/ApplicationTypeChoiceList.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form\ChoiceList;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ApplicationTypeChoiceList extends AbstractType
{
    private $appTypes;

    public function __construct($appTypeServices)
    {
        $this->appTypes = $appTypeServices;
    }

    public function setDefaultOptions(OptionsResolverInterface $options)
    {
        $options->setDefaults(array(
            'choices' => $this->appTypes,
        ));
    }


    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'applicationtype_choicelist';
    }
}

src/Markri/Bundle/OrganistBundle/Form/ChoiceList/BranchChoiceList.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form\ChoiceList;

use Symfony\Component\Form\AbstractType;
use Markri\Bundle\OrganistBundle\Entity\Application;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\OptionsResolver\Options;

class BranchChoiceList extends AbstractType
{

    /**
     * @var \Symfony\Component\DependencyInjection\ContainerInterface $container
     */
    protected $container;

    /**
     * @param $em
     */
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    /**
     * Loads the choice list
     * Should be implemented by child classes.
     *
     */
    protected function getChoices(Application $app)
    {
        /**
         * @var \Markri\Bundle\OrganistBundle\Versioning\VersioningInterface $versioningService
         */
        $versioningService = $this->container->get($app->getScmService());
        $branches = $versioningService->getBranches($app);
        $choices = array();

        foreach($branches as $branch){
            /**
             * @var \Markri\Bundle\OrganistBundle\Versioning\ReferenceInterface $branch
             */
            $choices[$branch->getName()] = $branch->getName();
        }

        return $choices;
    }



    public function getParent()
    {
        return 'choice';
    }


    /**
     * @param array $options
     * @return array
     */
    public function setDefaultOptions(OptionsResolverInterface $options)
    {

        $options->setDefaults(
            array(
                'label' => false,
                'empty_value' => '-- Choose a branch --',
                'app' => null,
                'choices' => function (Options $options){
                    return $this->getChoices($options['app']);
                }
            ));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'branch_choicelist';
    }
}

src/Markri/Bundle/OrganistBundle/Form/ChoiceList/EnvironmentType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */


namespace Markri\Bundle\OrganistBundle\Form\ChoiceList;

use Doctrine\ORM\EntityManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\OptionsResolver\Options;

class EnvironmentType extends AbstractType
{

    /**
     * @var EntityManager $em
     */
    protected $em;

    /**
     * @param EntityManager $em
     */
    public function __construct($em)
    {
        $this->em = $em;
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'environment_choicelist';
    }


    /**
     * @return null|string|\Symfony\Component\Form\FormTypeInterface
     */
    public function getParent()
    {
        return 'entity';
    }

    /**
     * @param array $options
     * @return array
     */
    public function setDefaultOptions(OptionsResolverInterface $options)
    {

        $options->setDefaults(
            array(
                'class' => 'OrganistBundle:Environment',
                'label' => false,
                'empty_value' => '-- Choose an environment --',
                'choices' => function (Options $options){
                    return $this->getChoices();
                }
            ));
    }

    /**
     * Loads the choice list
     *
     * Should be implemented by child classes.
     *
     * @return array with environements
     */
    protected function getChoices()
    {
        return $this->em->getRepository('OrganistBundle:Environment')->getOrderedByTypeAndHost();
    }
}

src/Markri/Bundle/OrganistBundle/Form/ChoiceList/ReferenceChoiceList.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form\ChoiceList;

use Symfony\Component\Form\AbstractType;
use Markri\Bundle\OrganistBundle\Entity\Application;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Form\Extension\Core\ChoiceList\SimpleChoiceList;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\OptionsResolver\Options;

class ReferenceChoiceList extends AbstractType
{

    /**
     * @var \Symfony\Component\DependencyInjection\ContainerInterface $container
     */
    protected $container;

    /**
     * @param $em
     */
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    /**
     * Loads the choice list
     * Should be implemented by child classes.
     *
     */
    protected function getChoices(Application $app)
    {
        /**
         * @var \Markri\Bundle\OrganistBundle\Versioning\VersioningInterface $versioningService
         */
        $versioningService = $this->container->get($app->getScmService());
        $references = $versioningService->getBranchesAndTags($app);
        $choices = array();

        foreach($references as $reference){
            /**
             * @var \Markri\Bundle\OrganistBundle\Versioning\ReferenceInterface $reference
             */
            $choices[$reference->getReference()] = $reference->getName();
        }

        return $choices;
    }



    public function getParent()
    {
        return 'choice';
    }


    /**
     * @param array $options
     * @return array
     */
    public function setDefaultOptions(OptionsResolverInterface $options)
    {

        $options->setDefaults(
            array(
                'label' => false,
                'empty_value' => '-- Choose a reference --',
                'app' => null,
                'choices' => function (Options $options){
                    return $this->getChoices($options['app']);
                }
            ));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'reference_choicelist';
    }

    /**
     * @param FormView $view
     * @param FormInterface $form
     * @param array $options
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        /**
         * @var SimpleChoiceList $choiceList
         */
        $choiceList = $options['choice_list'];

        if (count($choiceList->getChoices()) > 10) {
            $view->vars['attr']['class'] = 'bigrevisionselect';
            $view->vars['attr']['style'] = 'width: 100%';
        } else {
            $view->vars['attr']['class'] = 'form-control';
        }
    }
}

src/Markri/Bundle/OrganistBundle/Form/ChoiceList/StrategyType.php
<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Markri\Bundle\OrganistBundle\Form\ChoiceList;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class StrategyType extends AbstractType
{
    private $strategies;

    public function __construct($strategies)
    {
        $this->strategies = $strategies;
    }

    public function setDefaultOptions(OptionsResolverInterface $options)
    {
        $options->setDefaults(array(
            'choices' => $this->strategies,
        ));
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'strategy_choicelist';
    }
}

src/Markri/Bundle/OrganistBundle/Resources/views/Form/extended_div_layout.html.twig
{% extends 'form_div_layout.html.twig' %}


{# to prevent numbering collection items #}
{% block form_label %}
    {% spaceless %}
        {% if label is not sameas(false) %}
            {% if not compound %}
                {% set label_attr = label_attr|merge({'for': id}) %}
            {% endif %}
            {% if required %}
                {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
            {% endif %}

            {% if label is empty and compound %}

            {% else %}
                {% if label is empty %}
                    {% set label = name|humanize %}
                {% endif %}
                <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>{{ label|trans({}, translation_domain) }}</label>
            {% endif %}

        {% endif %}
    {% endspaceless %}
{% endblock form_label %}

{# implements twitter bootstrap horizontal forms #}
{% block form_row %}
    {% spaceless %}
        <div class="form-group {% if form_errors(form) | length > 0 %}has-error has-feedback{% endif %}">
            {% if form.parent.vars.attr['data-horizontal'] is defined %}
                {% set horizontal = form.parent.vars.attr['data-horizontal'] %}
            {% else %}
                {% set horizontal = false %}
            {% endif %}

            {% if horizontal %}
                {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' control-label col-lg-2')|trim}) %}
            {% endif %}
            {{ form_label(form, label, {'label_attr': label_attr}) }}

            {% set attr = attr|merge({'class': (attr.class|default('') ~ ' form-control')|trim}) %}
            {% if horizontal %}
                <div class="col-lg-10">
                    {{ form_widget(form, {'attr': attr}) }}
                    {% if form_errors(form) | length > 0 %}
                        <span class="help-block">{{ form_errors(form) }}</span>
                    {% endif %}
                    {% if attr['data-help'] is defined %}
                        <span class="help-block">{{ attr['data-help'] }}</span>
                    {% endif %}
                </div>
            {% else %}
                {{ form_widget(form, {'attr': attr}) }}
                {% if form_errors(form) | length > 0 %}
                    <span class="help-block">{{ form_errors(form) }}</span>
                {% endif %}
                {% if attr['data-help'] is defined %}
                    <span class="help-block">{{ attr['data-help'] }}</span>
                {% endif %}
            {% endif %}



        </div>
    {% endspaceless %}
{% endblock form_row %}

{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
        {% for error in errors %}
            {{ error.message }}
        {% endfor %}
    {% endif %}
{% endspaceless %}
{% endblock %}


{% block onetomany_row %}
    {% spaceless %}
        <div class="form-group">
            {% if form.parent.vars.attr['data-horizontal'] is defined %}
                {% set horizontal = form.parent.vars.attr['data-horizontal'] %}
            {% else %}
                {% set horizontal = false %}
            {% endif %}

            {% if horizontal %}
                {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' control-label col-lg-2')|trim}) %}
            {% endif %}
            {{ form_label(form, label, {'label_attr': label_attr}) }}
            {{ form_errors(form) }}
        </div>

        {{ form_widget(form, {'attr': attr}) }}

    {% endspaceless %}
{% endblock %}


{% block onetomany_widget %}

    {% if form.vars.layoutmacro == 'self' %}
        {% import 'OrganistBundle:Form:macro-onetomany.html.twig' as mymacro %}
    {% else %}
        {% import form.vars.layoutmacro as mymacro %}
    {% endif %}

    <div class="onetomanycontainer" data-prototype="{{  mymacro.onetomanyfields(form.vars.prototype) | escape('html') }}">

        {# iterate over each existing tag and render its only field: name #}
        {% for childform in form %}
            <div class="form-group">
                {{ mymacro.onetomanyfields(childform) }}
            </div>
        {% endfor %}
    </div>
{% endblock %}


{% macro onetomanyfields(fields) %}

    {% for childwidget in fields %}
        <div class="col-lg-2"></div>
        <div class="col-lg-9">
            {{ form_widget(childwidget,  {'attr': {'class': 'form-control'} }) }}
        </div>
    {% endfor %}
{% endmacro %}


{# implements inline radio/checkboxes with twitterbootstrap#}
{% block choice_widget_expanded %}
    {% spaceless %}
        <div {{ block('widget_container_attributes') }}>
            {% for child in form %}
                <label class="{% if multiple %}checkbox-inline{% else %}radio-inline{% endif %}">
                    {{ form_widget(child) }}
                    {{ child.vars.label }}
                </label>
            {% endfor %}
        </div>
    {% endspaceless %}
{% endblock choice_widget_expanded %}

src/Markri/Bundle/OrganistBundle/Resources/views/Form/macro-onetomany-userfiles.html.twig
{% macro onetomanyfields(fields) %}
    <div class="col-lg-2"></div>

    <div class="col-lg-2">
        {{ form_widget(fields.type) }}

    </div>
    <div class="col-lg-6">
        {{ form_widget(fields.path, {'attr': {'class': 'form-control'}}) }}
    </div>
{% endmacro %}

src/Markri/Bundle/OrganistBundle/Resources/views/Form/macro-onetomany.html.twig
{% macro onetomanyfields(fields) %}
    {% for childwidget in fields %}
        <div class="col-lg-2"></div>
        <div class="col-lg-9">
            {{ form_widget(childwidget,  {'attr': {'class': 'form-control'} }) }}
        </div>
    {% endfor %}
{% endmacro %}